/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/verordnungen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["anlegen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/termine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buchen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/termine/suche": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["suchen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/termine/pruefung": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pruefen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verordnungen/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ansehen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kalender/woche": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["woche"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/abrechnung/uebersicht": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["uebersicht"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Fehler: {
            fehler?: string;
        };
        VerordnungAnlage: {
            /** Format: date */
            ausstellungsdatum?: string;
            dringlicherBedarf?: boolean;
            diagnosegruppe?: string;
            /** Format: int32 */
            verordneteEinheiten?: number;
            /** Format: int32 */
            frequenzMin?: number;
            /** Format: int32 */
            frequenzMax?: number;
        };
        VerordnungAngelegt: {
            /** Format: uuid */
            id?: string;
        };
        Buchung: {
            /** Format: uuid */
            verordnung?: string;
            heilmittel?: string;
            therapeut?: string;
            raum?: string;
            /** Format: date-time */
            beginn?: string;
            uebersteuerung?: components["schemas"]["Uebersteuerung"];
        };
        Uebersteuerung: {
            begruendung?: string;
            von?: string;
        };
        Buchungsantwort: {
            /** Format: uuid */
            termin?: string;
            ausgang?: string;
            regeln?: components["schemas"]["Regel"][];
        };
        Regel: {
            regel?: string;
            ausgang?: string;
            begruendung?: string;
        };
        Suche: {
            /** Format: uuid */
            verordnung?: string;
            heilmittel?: string;
            /** Format: date */
            von?: string;
            /** Format: date */
            bis?: string;
            fruehestens?: string;
            spaetestens?: string;
            wochentage?: ("MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY")[];
        };
        Suchantwort: {
            zusammenfassung?: string;
            vorschlaege?: components["schemas"]["Terminvorschlag"][];
            ausgeschlossen?: {
                [key: string]: number;
            };
            /** Format: int32 */
            geprueft?: number;
        };
        Terminvorschlag: {
            /** Format: date-time */
            beginn?: string;
            /** Format: date-time */
            ende?: string;
            therapeut?: string;
            raum?: string;
            warnungen?: components["schemas"]["Regel"][];
        };
        Abrechnungsposten: {
            /** Format: uuid */
            verordnung?: string;
            /** Format: date */
            ausstellungsdatum?: string;
            diagnosegruppe?: string;
            therapieform?: string;
            /** Format: int32 */
            verordnet?: number;
            /** Format: int32 */
            erbracht?: number;
            /** Format: int32 */
            offen?: number;
            /** Format: date */
            ersteBehandlung?: string;
            /** Format: date */
            letzteBehandlung?: string;
            status?: string;
            begruendung?: string;
            regeln?: components["schemas"]["Regel"][];
        };
        Verordnungsakte: {
            posten?: components["schemas"]["Abrechnungsposten"];
            dringlicherBedarf?: boolean;
            /** Format: int32 */
            frequenzMin?: number;
            /** Format: int32 */
            frequenzMax?: number;
            frequenz?: string;
        };
        Belegung: {
            art?: string;
            /** Format: date-time */
            von?: string;
            /** Format: date-time */
            bis?: string;
            text?: string;
            raum?: string;
        };
        Spalte: {
            therapeut?: string;
            belegungen?: components["schemas"]["Belegung"][];
        };
        Woche: {
            /** Format: date */
            montag?: string;
            tagesbeginn?: string;
            tagesende?: string;
            /** Format: int32 */
            ruestzeitMinuten?: number;
            /** Format: int32 */
            nachruheMinuten?: number;
            spalten?: components["schemas"]["Spalte"][];
        };
        Abrechnungsuebersicht: {
            posten?: components["schemas"]["Abrechnungsposten"][];
            /** Format: int32 */
            erbracht?: number;
            /** Format: int32 */
            prueffest?: number;
            /** Format: int32 */
            beanstandet?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    anlegen: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Die Praxis, für die die Anfrage gilt. Platzhalter für Authentifizierung: In einer echten Anwendung käme der Mandant aus einem signierten Token.
                 * @example praxis-a
                 */
                "X-Mandant": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerordnungAnlage"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VerordnungAngelegt"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
        };
    };
    buchen: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Die Praxis, für die die Anfrage gilt. Platzhalter für Authentifizierung: In einer echten Anwendung käme der Mandant aus einem signierten Token.
                 * @example praxis-a
                 */
                "X-Mandant": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Buchung"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Buchungsantwort"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
        };
    };
    suchen: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Die Praxis, für die die Anfrage gilt. Platzhalter für Authentifizierung: In einer echten Anwendung käme der Mandant aus einem signierten Token.
                 * @example praxis-a
                 */
                "X-Mandant": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Suche"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Suchantwort"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
        };
    };
    pruefen: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Die Praxis, für die die Anfrage gilt. Platzhalter für Authentifizierung: In einer echten Anwendung käme der Mandant aus einem signierten Token.
                 * @example praxis-a
                 */
                "X-Mandant": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Buchung"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Buchungsantwort"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
        };
    };
    ansehen: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Die Praxis, für die die Anfrage gilt. Platzhalter für Authentifizierung: In einer echten Anwendung käme der Mandant aus einem signierten Token.
                 * @example praxis-a
                 */
                "X-Mandant": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Verordnungsakte"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
        };
    };
    woche: {
        parameters: {
            query?: {
                tag?: string;
            };
            header: {
                /**
                 * @description Die Praxis, für die die Anfrage gilt. Platzhalter für Authentifizierung: In einer echten Anwendung käme der Mandant aus einem signierten Token.
                 * @example praxis-a
                 */
                "X-Mandant": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Woche"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
        };
    };
    uebersicht: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Die Praxis, für die die Anfrage gilt. Platzhalter für Authentifizierung: In einer echten Anwendung käme der Mandant aus einem signierten Token.
                 * @example praxis-a
                 */
                "X-Mandant": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Abrechnungsuebersicht"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fehler"];
                };
            };
        };
    };
}
