/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/erfassung": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Erfassung */
        post: operations["erfassung_erfassung_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Erfassung
         * @description Die Antwort des Dienstes: der Vorschlag und was auf dem Weg dorthin geschah.
         */
        Erfassung: {
            vorschlag: components["schemas"]["VerordnungVorschlag"];
            /**
             * Pseudonymisiert
             * @description Wie viele Angaben vor dem Aufruf ersetzt wurden.
             */
            pseudonymisiert: number;
            /** Provider */
            provider: string;
        };
        /** Freitext */
        Freitext: {
            /** Text */
            text: string;
        };
        /**
         * Frequenz
         * @description Behandlungen je Woche als Spanne. Eine feste Zahl ist eine Spanne mit min gleich max.
         */
        Frequenz: {
            /** Min Pro Woche */
            min_pro_woche: number;
            /** Max Pro Woche */
            max_pro_woche: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerordnungVorschlag
         * @description Die strukturierte Verordnung, wie das Modell sie aus dem Freitext liest.
         */
        VerordnungVorschlag: {
            /** Heilmittel */
            heilmittel?: ("KG_EINZEL" | "KG_GRUPPE" | "MANUELLE_THERAPIE" | "KLASSISCHE_MASSAGE" | "MLD_TEILBEHANDLUNG" | "MLD_GROSSBEHANDLUNG" | "MLD_GANZBEHANDLUNG" | "KG_ZNS_ERWACHSENE" | "KG_ZNS_KINDER" | "KG_GERAET" | "KG_BEWEGUNGSBAD" | "WARMPACKUNG" | "ERGO_MOTORISCH_FUNKTIONELL" | "ERGO_SENSOMOTORISCH" | "ERGO_HIRNLEISTUNGSTRAINING" | "ERGO_PSYCHISCH_FUNKTIONELL" | "ERGO_BERATUNG_UMFELD") | null;
            /** Diagnosegruppe */
            diagnosegruppe?: ("WS" | "EX" | "CS" | "AT" | "GE" | "SO" | "LY" | "ZN" | "PN") | null;
            /** Verordnete Einheiten */
            verordnete_einheiten?: number | null;
            frequenz?: components["schemas"]["Frequenz"] | null;
            /** Ausstellungsdatum */
            ausstellungsdatum?: string | null;
            /** Dringlicher Bedarf */
            dringlicher_bedarf?: boolean | null;
            /** Hausbesuch */
            hausbesuch?: boolean | null;
            /**
             * Nicht Extrahierbar
             * @description Felder, die im Text fehlen oder sich widersprechen. Nie raten.
             */
            nicht_extrahierbar?: ("heilmittel" | "diagnosegruppe" | "verordnete_einheiten" | "frequenz" | "ausstellungsdatum" | "dringlicher_bedarf" | "hausbesuch")[];
            /**
             * Hinweise
             * @description Was am Text auffällt: Widersprüche, Unleserliches, Ungewöhnliches.
             */
            hinweise?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    erfassung_erfassung_post: {
        parameters: {
            query?: never;
            header: {
                "X-Mandant": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Freitext"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erfassung"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
